Repository caas-team/py-kube-downscaler, pull requests merged in 2024-04, with the labels that each got.

#12 Fix existing issues with labels and resources
  kube_downscaler/scaler.py
Labels: fix

#13 fix: moved template to .github folder
  .github/pull_request_template.md
Labels: fix

#17 add helm build wf
  .github/workflows/helm-build.yml
Labels: feature

#15 feat/e2e-test-pipeline
  .github/workflows/docker-build.yml
  .github/workflows/end2end.yml
  chart/Chart.yaml
  chart/templates/_helpers.tpl
  chart/templates/configmap.yaml
  chart/templates/deployment.yaml
  chart/templates/rbac.yaml
  chart/values.yaml
Labels: feature

#22 fix helm rbac
  chart/Chart.yaml
  chart/templates/rbac.yaml
  chart/values.yaml
Labels: bug

#23 Feat/dispatch-event
  .github/workflows/helm-build.yml
Labels: enhancement

#21 Fix/refine-tagging-logic
  .github/workflows/docker-build.yml
Labels: enhancement
