Repository caas-team/py-kube-downscaler, pull requests merged in 2024-11, with the labels that each got.

#108 Chore: Update Dependencies November 2024, Release 24.11.0
  chart/Chart.yaml
  poetry.lock
  pyproject.toml
Labels: dependencies

#117 Fix: Api Server Timeout Argument Doesn't Override Default Timeout Value
  kube_downscaler/helper.py
  kube_downscaler/scaler.py
  tests/test_scaler.py
Labels: bug, fix

#120 Fix: Added imagePullSecret customization support
  chart/templates/deployment.yaml
Labels: bug, fix

#121 Fix: Test_Scale_Custom_Timeout After Merging
  tests/test_scaler.py
Labels: fix
