Repository caas-team/py-kube-downscaler, pull requests merged in 2024-05, with the labels that each got.

#25 Added extraConfig helm field, so configuration can be better describe…
  chart/Chart.yaml
  chart/README.md
  chart/templates/configmap.yaml
  chart/values.yaml
Labels: enhancement

#30 bump appVersion
  chart/Chart.yaml
Labels: enhancement

#14 Feat/pytest-action
  .github/workflows/python-tests.yml
  poetry.lock
  pyproject.toml
Labels: feature

#32 Feat/helmchart taking account about tolerations values into deployment template
  chart/Chart.yaml
  chart/templates/deployment.yaml
Labels: enhancement, feature

#35 Fix/deployment command
  README.md
  chart/README.md
Labels: housekeeping, fix

#38 Enhance/use new-pykube
  poetry.lock
  pyproject.toml
Labels: enhancement

#48 permission adjustments & run on PRs
  .github/workflows/python-tests.yml
Labels: enhancement

#56 Ensure configMapName Value is Used Consistently Across Templates
  chart/templates/configmap.yaml
Labels: enhancement, fix
