Repository caas-team/py-kube-downscaler, pull requests merged in 2024-10, with the labels that each got.

#99 Chore/bump to24.10.0
  .pre-commit-config.yaml
  README.md
  chart/Chart.yaml
Labels: housekeeping, fix

#100 Added ScaledObject Support For Downscaler/Downtime-Replicas Annotation
  README.md
  kube_downscaler/resources/keda.py
  kube_downscaler/scaler.py
  tests/test_autoscale_resource.py
  tests/test_resources.py
  tests/test_scaler.py
Labels: documentation, enhancement, feature

#101 Dependencies: October 2024 Update
  poetry.lock
Labels: dependencies

#102 Chore: Version 24.10.1
  chart/Chart.yaml
Labels: release

#104 fix: serviceaccount creation
  chart/templates/rbac.yaml
Labels: housekeeping
