Repository caas-team/py-kube-downscaler, pull requests merged in 2025-03, with the labels that each got.

#134 Chore/prune dev images
  .github/workflows/docker-build.yml
  .github/workflows/end2end.yml
  .github/workflows/prune.yml
Labels: housekeeping, fix, feature

#136 fix: non used values and bump dependencies
  .pre-commit-config.yaml
  chart/Chart.yaml
  chart/templates/deployment.yaml
  chart/templates/rbac.yaml
  chart/values.yaml
  poetry.lock
Labels: bug, dependencies, release

#137 chore: bump version in pyproject.toml
  pyproject.toml
Labels: release

#142 Chore/bump action
  .github/workflows/prune.yml
Labels: bug, housekeeping

#143 fix: move imagePullPolicy to container definition
  chart/templates/deployment.yaml
Labels: bug

#139 Added {{ .Release.Namespace }} Inside Helm Chart
  chart/Chart.yaml
  chart/templates/configmap.yaml
  chart/templates/deployment.yaml
  chart/templates/rbac.yaml
Labels: housekeeping

#146 chore: bump project version for new release
  pyproject.toml
Labels: release

#148 Fix/Broken Helm Chart When Using Multiple Constrained Namespaces
  chart/templates/rbac.yaml
Labels: bug

#149 feat: new release for helm chart fix
  chart/Chart.yaml
  pyproject.toml
Labels: release
